In [18]:
import numpy as np

In [24]:
# создание массива из списка
list_of_nums = [1,2,3]
a = np.array(list_of_nums)
print(type(a))
print(a.shape)

<class 'numpy.ndarray'>
(3,)


In [25]:
# создание массивов с помощью встроенных функций
a = np.ones((4,4))
b = np.eye(4)
print(a)
print(b)
print(a + b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[2. 1. 1. 1.]
 [1. 2. 1. 1.]
 [1. 1. 2. 1.]
 [1. 1. 1. 2.]]


In [26]:
# создание массива последовательности и форматированный вывод
np.set_printoptions(precision = 1)
print(np.arange(0, 1, 0.01))

[0.  0.  0.  0.  0.  0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.2 0.2
 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.4
 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5
 0.5 0.6 0.6 0.6 0.6 0.6 0.6 0.6 0.6 0.6 0.6 0.7 0.7 0.7 0.7 0.7 0.7 0.7
 0.7 0.7 0.7 0.8 0.8 0.8 0.8 0.8 0.8 0.8 0.8 0.8 0.8 0.8 0.9 0.9 0.9 0.9
 0.9 0.9 0.9 0.9 0.9 1.  1.  1.  1.  1. ]


In [33]:
a = np.empty((3,2,4))
print(f"Форма массива {a.shape}")
print(f"Тип данных массива {a.dtype}")

Форма массива (3, 2, 4)
Тип массива float64


In [43]:
a = np.arange(0, 10, 1)
print(f"a = {a}")
print(f"Индекс 0 = {a[0]}, индекс 9 = {a[9]}")
print(f"Срез со 2 по 4 эелемент включительно {a[1:5]}")

a = [0 1 2 3 4 5 6 7 8 9]
Индекс 0 = 0, индекс 9 = 9
Срез со 2 по 4 эелемент включительно [1 2 3 4]


In [47]:
a = np.eye(3)
b = np.ones((3,3))
print(f"Поэлементное сложение \n {a + b}")
print(f"Поэлементное умножение \n {a * b}")

Поэлементное сложение 
 [[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]
Поэлементное умножение 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [52]:
a = np.array([1,1,1,2,3,4])
print(f"Среднее арифметическое {np.mean(a)}")
print(f"Медиана {np.median(a)}")

Среднее арифметическое 2.0
Медиана 1.5


In [67]:
# Пример с оценками
grades = np.array([[4,5,4],[3,4,5],[5,4,3]])
titles = np.array(["Математика", "Литература", "ОБЖ"])
print("Среднее по предментам:")
for i in range(titles.size):
    print(f"{titles[i]}: {np.mean(grades[i]):.2f}") 

print(f"Среднее по всем {np.mean(grades):.2f}")

Среднее по предментам:
Математика: 4.33
Литература: 4.00
ОБЖ: 4.00
Среднее по всем 4.11


In [71]:
# Пример с температурой
week_temps = np.array([12.5, 14.0, 13.2, 15.1, 16.8, 18.0, 17.3])
print("Температуры по дням недели:", week_temps)
print("Минимальная температура:", np.min(week_temps))
print("Максимальная температура:", np.max(week_temps))
print(f"Средняя температура: {np.mean(week_temps):.2f}")

Температуры по дням недели: [12.5 14.  13.2 15.1 16.8 18.  17.3]
Минимальная температура: 12.5
Максимальная температура: 18.0
Средняя температура: 15.27


In [74]:
# Пример с покупками
sales = np.array([[120, 80, 60], [150, 90, 70],[130, 110, 65]])
categories = np.array(["Еда", "Быт", "Одежда"])
print("Общие покупки по категориям:")
for i in range(categories.size):
    print(f"{categories[i]}: {np.sum(sales[:, i])} руб")

Общие покупки по категориям:
Еда: 400 руб
Быт: 280 руб
Одежда: 195 руб
